#!/usr/bin/env python3
"""Generate ``docs/format_support.md`` from the in-process codec registry.

Idempotent: produces a deterministic Markdown table and writes it
to ``docs/format_support.md``. CI verifies that re-running this script
leaves no diff (see ``just docs-check`` in the justfile).
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from tablecodec import codecs
from tablecodec.codecs.fintabnet import FinTabNetCodec
from tablecodec.codecs.otsl import OTSL10Codec
from tablecodec.codecs.pubtabnet import PubTabNet10Codec, PubTabNet20Codec
from tablecodec.codecs.tablebank import TableBankCodec
from tablecodec.codecs.tableformer import TableFormerCodec

# Seed built-in codecs deterministically — order shapes the rendered table.
_BUILTINS = [
    PubTabNet10Codec(),
    PubTabNet20Codec(),
    FinTabNetCodec(),
    TableFormerCodec(),
    TableBankCodec(),
    OTSL10Codec(),
]

_OUT = Path(__file__).parent.parent / "docs" / "format_support.md"


def _format_lossy(values: frozenset[str]) -> str:
    if not values:
        return "—"
    return ", ".join(f"`{v}`" for v in sorted(values))


def _seed_registry() -> None:
    saved = codecs._snapshot()  # type: ignore[attr-defined]
    codecs._restore({})  # type: ignore[attr-defined]
    for codec in _BUILTINS:
        if codec.name not in codecs.list_codecs():
            codecs.register(codec)
    del saved  # silence


def _render() -> str:
    header = dedent(
        """\
        # Format Support

        Auto-generated by `scripts/gen_format_support.py`. Do not edit by hand.

        | Codec | Spec version | Media type | Loss on read | Loss on write |
        |---|---|---|---|---|
        """
    )
    rows: list[str] = []
    for name in codecs.list_codecs():
        codec = codecs.get(name)
        rows.append(
            "| `{name}` | {spec} | `{media}` | {lr} | {lw} |".format(
                name=codec.name,
                spec=codec.spec_version,
                media=codec.media_type,
                lr=_format_lossy(codec.lossy_read()),
                lw=_format_lossy(codec.lossy_write()),
            )
        )
    return header + "\n".join(rows) + "\n"


def main() -> int:
    _seed_registry()
    rendered = _render()
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {_OUT}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
