#!/usr/bin/env python3
"""Generate ``docs/loss_matrix.md`` from the in-process codec registry.

Renders an N×N matrix where cell (source, target) shows the
``round_trip_classification`` returned by ``analyze_loss``. Idempotent
so CI can verify the committed file matches a fresh regeneration.
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from tablecodec import analyze_loss, codecs
from tablecodec.codecs.otsl import OTSL10Codec
from tablecodec.codecs.pubtabnet import PubTabNet10Codec, PubTabNet20Codec

_BUILTINS = [
    PubTabNet10Codec(),
    PubTabNet20Codec(),
    OTSL10Codec(),
]

_OUT = Path(__file__).parent.parent / "docs" / "loss_matrix.md"

_CLASS_GLYPH = {
    "lossless": "🟢 lossless",
    "structure-preserving": "🟡 structure",
    "lossy": "🔴 lossy",
}


def _seed_registry() -> None:
    codecs._restore({})  # type: ignore[attr-defined]
    for codec in _BUILTINS:
        codecs.register(codec)


def _render() -> str:
    names = sorted(codecs.list_codecs())
    header_cells = ["source \\ target", *names]
    header = "| " + " | ".join(header_cells) + " |"
    sep = "|" + "|".join(["---"] * len(header_cells)) + "|"
    body_lines: list[str] = []
    for source in names:
        row = [f"`{source}`"]
        for target in names:
            report = analyze_loss(source=source, target=target)
            row.append(_CLASS_GLYPH[report.round_trip_classification])
        body_lines.append("| " + " | ".join(row) + " |")
    intro = dedent(
        """\
        # Loss Matrix

        Auto-generated by `scripts/gen_loss_matrix.py`. Do not edit by hand.

        Each cell shows the static `round_trip_classification` returned by
        `analyze_loss(source, target)`:

        - 🟢 **lossless** — nothing dropped on either side.
        - 🟡 **structure-preserving** — only auxiliary fields lost
          (`bbox`, `role`, `extras`). Grid topology and cell tokens
          survive the round trip.
        - 🔴 **lossy** — at least one structural / content field lost.

        """
    )
    return intro + header + "\n" + sep + "\n" + "\n".join(body_lines) + "\n"


def main() -> int:
    _seed_registry()
    rendered = _render()
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {_OUT}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
